name: Cucumber-Selenium-Java-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 20
      uses: actions/setup-java@v3.10.0
      with:
        java-version: '20'
      
    - name: Build with Maven
      run: mvn -B clean package -DskipTests
      
    - name: Run cucumber for upastream poc
      run: mvn test
