name: Cucumber Selenium Upstream poc

on:
  workflow_dispatch:
    inputs:
      slack_message:
        description: 'run test'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
       
      - name: Run Cucumber tests
        run: mvn clean test
        
      - name: Publish Cucumber HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: Cucumber-Report
          path: target/cucumber-reports
          
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: QA Team
          SLACK_MSG_AUTHOR: "Please fin here automation test report. Regards"
          SLACK_TITLE: Core plugin reporting test
          SLACK_COLOR: ${{job.status}}

